In [ ]:
import pandas as pd

In [ ]:
data=pd.read_excel(r"/content/batch 8 dataset-sales data.xlsx")

Part A: Basic Understanding

1. Load the dataset using Pandas and display the first 10 rows.

In [ ]:
data.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,NaN,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin
6,NaN,10457,2022-11-08 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Remy Monet,Paris
7,NaN,10459,2022-11-08 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Walter Muller,Berlin
8,NaN,10460,2022-11-09 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Remy Monet,Paris
9,NaN,10461,2022-11-09 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Remy Monet,Paris

2.Find the total number of rows and columns.

In [ ]:
data.shape

(255, 10)

3.List all column names.

In [ ]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

4.Check data types of each column.

In [ ]:
data.dtypes

Unnamed: 0    float64
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
dtype: object

5.Identify missing or null values.

In [ ]:
data.isnull().sum()

Unnamed: 0    255
Unnamed: 1      0
Unnamed: 2      0
Unnamed: 3      0
Unnamed: 4      0
Unnamed: 5      0
Unnamed: 6      0
Unnamed: 7      0
Unnamed: 8      0
Unnamed: 9      0
dtype: int64

Part B: Data Cleaning & Preparation
6. Handle missing values appropriately and explain your method in comments.

In [ ]:
data=data.fillna(0)

In [ ]:
data.isnull().sum()

Unnamed: 0    0
Unnamed: 1    0
Unnamed: 2    0
Unnamed: 3    0
Unnamed: 4    0
Unnamed: 5    0
Unnamed: 6    0
Unnamed: 7    0
Unnamed: 8    0
Unnamed: 9    0
dtype: int64

7.Check for duplicate records and remove them if present.

In [ ]:
duplicates = data.duplicated().sum()
print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

8.Check for duplicate records and remove them if present.

In [ ]:
data.dtypes

Unnamed: 0    float64
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
dtype: object

In [ ]:
data = data.rename(columns={
'Unnamed: 1': 'Order ID',
'Unnamed: 2': 'Date',
'Unnamed: 3': 'Product',
'Unnamed: 4': 'Price',
'Unnamed: 5': 'Quantity',
'Unnamed: 6': 'Purchase Type',
'Unnamed: 7': 'Payment Method',
'Unnamed: 8': 'Manager',
'Unnamed: 9': 'City'
})
# Remove the first row which contains the old headers as data
data = data.iloc[1:].copy()
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Price'] = pd.to_numeric(data['Price'], errors='coerce')
# Convert 'Quantity' to numeric, then round to nearest integer, then to nullable integer data['Quantity'] = pd.to_numeric(data['Quantity'], errors='coerce').round().astype
data['Product'] = data['Product'].astype('category')
data['Purchase Type'] = data['Purchase Type'].astype('category')
data['Payment Method'] = data['Payment Method'].astype('category')
data['Manager'] = data['Manager'].astype('category')
data['City'] = data['City'].astype('category')

In [ ]:
data.dtypes

Unnamed: 0               float64
Order ID                  object
Date              datetime64[ns]
Product                 category
Price                    float64
Quantity                  object
Purchase Type           category
Payment Method          category
Manager                 category
City                    category
dtype: object

9.Create a new column: Total Sales = Quantity × Unit Price (if not already present).

In [ ]:
data['Quantity'] = pd.to_numeric(data['Quantity'], errors='coerce').round().astype('Int64')
data['Price'] = pd.to_numeric(data['Price'], errors='coerce')
data['Total_Sales'] = data['Quantity'] * data['Price']

In [ ]:
print(data[['Quantity', 'Price', 'Total_Sales']].head())

   Quantity  Price  Total_Sales
1       573   3.49      1999.77
2       746   2.95       2200.7
3       200   4.99        998.0
4       570  12.99       7404.3
5       201   9.95      1999.95

10.Extract useful information from date column (year, month, etc.).

In [ ]:
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day
data['Weekday'] = data['Date'].dt.day_name()

In [ ]:
print(data[['Date', 'Year', 'Month', 'Day', 'Weekday']].head())

        Date  Year  Month  Day  Weekday
1 2022-11-07  2022     11    7   Monday
2 2022-11-07  2022     11    7   Monday
3 2022-11-07  2022     11    7   Monday
4 2022-11-08  2022     11    8  Tuesday
5 2022-11-08  2022     11    8  Tuesday

Part C: Data Analysis
11. Find total sales by product.

In [ ]:
total_sales_by_product = data.groupby('Product')['Total_Sales'].sum()

In [ ]:
print(total_sales_by_product)

Product
Beverages              103214.6
Burgers               376943.82
Chicken Sandwiches    114612.45
Fries                 125626.57
Sides & Other           48902.0
Name: Total_Sales, dtype: Float64

12.Identify top 5 best-selling products.

In [ ]:
top_5_products = data.groupby('Product')['Total_Sales'].sum().nlargest(5)

In [ ]:
print(top_5_products)

Product
Burgers               376943.82
Fries                 125626.57
Chicken Sandwiches    114612.45
Beverages              103214.6
Sides & Other           48902.0
Name: Total_Sales, dtype: Float64

13. Analyze sales by region.

In [ ]:
sales_by_region = data.groupby('City')['Total_Sales'].sum()

In [ ]:
print(sales_by_region)

City
Berlin    100572.34
Lisbon    241635.49
London    211160.04
Madrid    136154.24
Paris      79777.33
Name: Total_Sales, dtype: Float64

14. Find monthly sales trends.

In [ ]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Year_Month'] = data['Date'].dt.to_period('M')
monthly_sales = data.groupby('Year_Month')['Total_Sales'].sum()
print(monthly_sales)

Year_Month
2022-11    332015.12
2022-12    437284.32
Freq: M, Name: Total_Sales, dtype: Float64

15.Identify highest revenue-generating category.

In [ ]:
category_sales = data.groupby('Product')['Total_Sales'].sum()
top_category = category_sales.idxmax()
top_value = category_sales.max()

In [ ]:
print(f"Top Category/Product: {top_category}, Total Sales: {top_value}")

Top Category/Product: Burgers, Total Sales: 376943.82

16. Calculate average sales per transaction.

In [ ]:
average_sales = data['Total_Sales'].mean()
print(f"Average Sales per Transaction: {average_sales}")

Average Sales per Transaction: 3028.737952755905

Part D: Advanced Analysis
17. Identify products with high sales but low profit (if cost data available).

In [ ]:
data['Total_Sales'] = data['Quantity'] * data['Price']

In [ ]:
print(f'Total sales: {data["Total_Sales"].sum()}')

Total sales: 769299.44

18. Analyze seasonal trends in sales.

In [ ]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Year_Month'] = data['Date'].dt.to_period('M')
data['Month'] = data['Date'].dt.month
monthly_sales = data.groupby('Month')['Total_Sales'].sum()
print(monthly_sales)

Month
11    332015.12
12    437284.32
Name: Total_Sales, dtype: Float64

19. Detect any unusual spikes or drops in sales (outliers)

In [ ]:
Q1 = data['Total_Sales'].quantile(0.25)
Q3 = data['Total_Sales'].quantile(0.75)
IQR = Q3 - Q1
outliers = data[(data['Total_Sales'] < Q1 - 1.5 * IQR) | (data['Total_Sales'] > Q3 + 1.5 * IQR)]
print(outliers)

     Unnamed: 0 Order ID       Date             Product  Price  Quantity  \
3           0.0    10454 2022-11-07       Sides & Other   4.99       200
4           0.0    10455 2022-11-08             Burgers  12.99       570
7           0.0    10459 2022-11-08       Sides & Other   4.99       200
8           0.0    10460 2022-11-09             Burgers  12.99       554
12          0.0    10464 2022-11-09       Sides & Other   4.99       200
..          ...      ...        ...                 ...    ...       ...
245         0.0    10704 2022-12-27       Sides & Other   4.99       200
246         0.0    10705 2022-12-28             Burgers  12.99       724
247         0.0    10706 2022-12-28  Chicken Sandwiches   9.95       302
250         0.0    10709 2022-12-28       Sides & Other   4.99       200
251         0.0    10710 2022-12-29             Burgers  12.99       754

    Purchase Type Payment Method         Manager    City  Total_Sales  Year  \
3       In-store       Gift Card   Joao    Silva  Lisbon        998.0  2022
4       In-store     Credit Card   Walter Muller  Berlin       7404.3  2022
7       In-store     Credit Card   Walter Muller  Berlin        998.0  2022
8       In-store     Credit Card      Remy Monet   Paris      7196.46  2022
12      In-store     Credit Card  Remy     Monet   Paris        998.0  2022
..            ...            ...             ...     ...          ...   ...
245   Drive-thru       Gift Card   Walter Muller  Berlin        998.0  2022
246   Drive-thru       Gift Card   Walter Muller  Berlin      9404.76  2022
247   Drive-thru       Gift Card   Walter Muller  Berlin       3004.9  2022
250   Drive-thru       Gift Card   Walter Muller  Berlin        998.0  2022
251   Drive-thru       Gift Card   Walter Muller  Berlin      9794.46  2022

     Month  Day    Weekday Year_Month
3       11    7     Monday    2022-11
4       11    8    Tuesday    2022-11
7       11    8    Tuesday    2022-11
8       11    9  Wednesday    2022-11
12      11    9  Wednesday    2022-11
..     ...  ...        ...        ...
245     12   27    Tuesday    2022-12
246     12   28  Wednesday    2022-12
247     12   28  Wednesday    2022-12
250     12   28  Wednesday    2022-12
251     12   29   Thursday    2022-12

[104 rows x 16 columns]

20. Write five meaningful insights based on the dataset.

In [ ]:
print("Top 5 Products:\n", data.groupby('Product', observed=True)['Total_Sales'].sum().nlargest(5))

Top 5 Products:
 Product
Burgers               376943.82
Fries                 125626.57
Chicken Sandwiches    114612.45
Beverages              103214.6
Sides & Other           48902.0
Name: Total_Sales, dtype: Float64

Part E: NumPy Application
21. Convert sales or quantity column into a NumPy array.

In [ ]:
import numpy as np

In [ ]:
quantity_array = data['Quantity'].to_numpy()
sales_array = data['Total_Sales'].to_numpy()
print(quantity_array[:5])
print(sales_array[:5])

[573 746 200 570 201]
[1999.77 2200.7   998.   7404.3  1999.95]

22. Calculate mean, standard deviation, minimum, and maximum using
NumPy.

In [ ]:
sales_array = data['Total_Sales'].to_numpy()
mean_sales = np.mean(sales_array)
std_sales = np.std(sales_array)
min_sales = np.min(sales_array)
max_sales = np.max(sales_array)

In [ ]:
print(f"Mean: {mean_sales}, Std: {std_sales}, Min: {min_sales}, Max: {max_sales}")

Mean: 3028.737952755905, Std: 2415.1642016458336, Min: 998.0, Max: 16065.0

23. Compare NumPy results with Pandas results.

In [ ]:
mean_np = np.mean(sales_array)
std_np = np.std(sales_array)
min_np = np.min(sales_array)
max_np = np.max(sales_array)
mean_pd = data['Total_Sales'].mean()
std_pd = data['Total_Sales'].std()
min_pd = data['Total_Sales'].min()
max_pd = data['Total_Sales'].max()

In [ ]:
print("NumPy vs Pandas Statistics:")
print(f"Mean: {mean_np} | {mean_pd}")
print(f"Std: {std_np} | {std_pd}")
print(f"Min:{min_np} | {min_pd}")
print(f"Max:{max_np} | {max_pd}")

NumPy vs Pandas Statistics:
Mean: 3028.737952755905 | 3028.737952755905
Std: 2415.1642016458336 | 2419.9325462715055
Min:998.0 | 998.0
Max:16065.0 | 16065.0